### ISSUE TITLE
Handler should have an option to ignore messages from itself

### ISSUE THREAD

**Issue by lox** [kenjij/lita-slack-handler#1]
I've run into a hilarious issue where @lita help will create an infinite loop of help messages, as lita help prefixes its output with it's name. 

Would be great to have a way to stop this happening.

**Comment by agh** [comment]
```
  config.adapter.add_mention = true
```

That certainly does the trick for me.

**Comment by sciurus** [comment]
You can work around this with

`config.handlers.slack_handler.ignore_user_name = 'slackbot'`

At first I thought you would need to ignore the _mention_name_ you configured for your bot, but it seems that slack's outgoing webhooks set the username to _slackbot_ instead. It seems like lita-slack-handler should ignore messages from slackbot by default.

**Comment by jimmycuadra** [comment]
This issue is handled by the new lita-slack that uses Slack's realtime API!

**Comment by leejones** [comment]
nice! :sparkles:

**Comment by sciurus** [comment]
Thanks for your fast work on this @jimmycuadra !
