### ISSUE TITLE
Support for Lita 4.0?

### ISSUE THREAD

**Issue by dhc02** [kenjij/lita-slack-handler#4]
What will need to change, if anything, to support Lita 4 in lita-slack and lita-slack-handler? Just using the new config.adapters? Or is there more to it? http://docs.lita.io/releases/4/

**Comment by sciurus** [comment]
It seems to work.

**Comment by jimmycuadra** [comment]
lita-slack 1.0 was released today and works with Lita 4. This plugin is now a no-op!
